[package]
edition = "2021"
name = "rome_json_parser"
version = "0.1.0"
authors = [""]
license = "MIT"
description = "An extremely fast ECMAScript parser made for the rslint project"
# repository = "https://github.com/rslint/rslint"

[dependencies]
# rome_js_parser = { path = "../rome_js_parser" }
rome_json_syntax = { path = "../rome_json_syntax" }
# rome_js_syntax = { path = "../rome_js_syntax" }
rome_rowan = { path = "../rome_rowan" }
rome_diagnostics = { path = "../rome_diagnostics" }
drop_bomb = "0.1.5"
logos = "0.12.0"
# bitflags = "1.3.2"
# indexmap = "1.8.0"
# cfg-if = "1.0.0"
# smallvec = { version = "1.8.0", features = ["union", "const_new"] }
# tracing = { version = "0.1.31", default-features = false, features = ["std"] }

[dev-dependencies]
# tests_macros = { path = "../tests_macros" }
# expect-test = "1.2.2"
# quickcheck = "1.0.3"
# quickcheck_macros = "1.0.0"
