[package]
name = "rome_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rome_diagnostics = { path = "../rome_diagnostics" }
rome_rowan = { path = "../rome_rowan" }
# drop_bomb = "0.1.5"
# bitflags = "1.3.2"
# indexmap = "1.8.0"
# cfg-if = "1.0.0"
# smallvec = { version = "1.8.0", features = ["union", "const_new"] }
# tracing = { version = "0.1.31", default-features = false, features = ["std"] }
