[package]
name = "rome_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# use rome_js_syntax::{JsSyntaxKind, LanguageVariant};
# use rome_rowan::TextSize;

# pub type ParseDiagnostic = rome_diagnostics::Diagnostic;

rome_rowan = { path = "../rome_rowan" }
rome_diagnostics = { path = "../rome_diagnostics" }
